config/routes.rb
Buzzbuzz::Application.routes.draw do
  devise_for :users
  
  resources :topics
  resources :comments

  resources :users
  
  resources :items do |route|
    post 'vote'
  end
  
  match '/best' => 'root#best'
  match '/recent' => 'root#recent'
  match '/worst' => 'root#worst'
  

  root :to => "root#best"

end

app/models/comment.rb
class Comment < Item
  # Validates
  validates :parent, :presence => true
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!

  # GET /comments/new
  # GET /comments/new.xml
  def new
    @comment = Comment.new

    respond_to do |format|
      format.js
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.xml
  def create
    parent = Item.find(params[:comment][:parent])
    params[:comment][:parent] = nil
    
    @comment = Comment.new(params[:comment])
    @comment.author = current_user
    @comment.parent = parent

    respond_to do |format|
      if @comment.save
        format.html { redirect_to(item_path(@comment.root), :notice => 'Comment was successfully created.') }
      else
        format.html { redirect_to :back }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.xml
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to(@comment, :notice => 'Comment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.xml
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to(comments_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def vote_status(item, clazz)
    if !user_signed_in?
      return clazz
    end
    
    vote = Vote.find_by_user_item(current_user, item)
    
    if vote == nil
      return clazz
    end
    
    if vote.vote == 1 && clazz == :btn_up
      return [:btn_up, :btn_up_selected]
    elsif vote.vote == -1 && clazz == :btn_down
      return [:btn_down, :btn_down_selected]
    end
    
    clazz
  end
end

app/views/comments/_comment.html.erb
<!--a feed-->
<div id="item<%=comment.id%>" class="buzz_feed">
<!-- corners -->
	<div class="round_10_tl corner_tl"></div>
	<div class="round_10_tr corner_tr"></div>
	<div class="round_10_bl corner_bl"></div>
	<div class="round_10_br corner_br"></div>
	<!-- control bar-->
	<div id="buzz_control" class="buzz_control rate_fav">
		
		<%= link_to "", item_vote_path(comment, :score => "1", :format => :js), :method => :post, :class => vote_status(comment, :btn_up), :remote => :true %>
		<p id="buzz_rate" class="buzz_rate"><%= comment.score %></p>
		<%= link_to "", item_vote_path(comment, :score => "-1", :format => :js), :method => :post, :class => vote_status(comment, :btn_down), :remote => :true %>

	</div>

	<!-- feed content -->
	<div id="buzz_content_holder" class="buzz_content_holder">
    <%= link_to comment.author.username, "", :class => :buzz_author, :id => :author %>
    <%= t(:post_at) %>
		<span id="time" class="buzz_time"><%= time_ago_in_words comment.created_at %></span>
		<%= t(:ago) %>
		|<%= link_to "链接", item_path(comment) %>
		<% if params[:id].to_i == comment.id %>
		|<%= link_to "父嗡嗡", item_path(comment.parent) %>
		<% end %>

		<p class="buzz_content"><%= comment.text %></p>

	</div>
	
	<div id="buzz_comment" class="buzz_comment">
	  <%= link_to "嗡一下", new_comment_path(:parent => comment), :remote => :true %>
	</div>
	


</div>
<!--end of a feed-->

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <p class="clearfix"><%= f.label :text %>:<br />
  <%= f.text_area :text, :class => :post_input, :rows => 10 %></p>
  <%= f.hidden_field :parent, :value => params[:parent] %>
  
  <div class="actions">
    <%= f.submit :class => :btn_submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/new.js.erb
$("#comment_form").dialog({
  autoOpen: true,
  modal: true,
  width: 480,
  title: 'Reply to',
  position: ['center', 200],
  open: function() {
    disable_scroll()
    $("#comment_form").html("<%= escape_javascript(render('form')) %>")
  },
  close: enable_scroll
});

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>