config/routes.rb
Buzzbuzz::Application.routes.draw do
  devise_for :users
  
  resources :topics
  resources :comments

  resources :users
  
  resources :items do |route|
    post 'vote'
  end
  
  match '/best' => 'root#best'
  match '/recent' => 'root#recent'
  match '/worst' => 'root#worst'
  

  root :to => "root#best"

end

app/models/topic.rb
class Topic < Item
  # Validates
  validates :title, :presence => true,
                    :length => { :maximum => 30 }
  
  validates :url, :presence => true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /topics/new
  # GET /topics/new.xml
  def new
    @topic = Topic.new

    respond_to do |format|
      format.js
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.xml
  def create
    @topic = Topic.new(params[:topic])
    @topic.author = current_user

    respond_to do |format|
      if @topic.save
        format.html { redirect_to(item_path(@topic), :notice => 'Topic was successfully created.') }
        format.xml  { render :xml => @topic, :status => :created, :location => @topic }
      else
        format.html { redirect_to :back }
        format.xml  { render :xml => @topic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.xml
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to(@topic, :notice => 'Topic was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @topic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.xml
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to(topics_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def tree_count(item, is_root = true)
    result = is_root ? 0 : 1
    item.children.each do |x|
      result += tree_count x, false
    end
    result
  end
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <p class="clearfix"><%= f.label :title %>:<br />
  <%= f.text_field :title, :class => :post_input %></p>
  
  <p class="clearfix"><%= f.label :url %>:<br />
  <%= f.url_field :url, :class => :post_input %></p>
  
  <p class="clearfix"><%= f.label :text %>:<br />
  <%= f.text_area :text, :class => :post_input, :rows => 10 %></p>
  
  <div class="actions clearfix">
    <%= f.submit :class => :btn_submit %>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<!--a feed-->
<div id="item<%=topic.id%>" class="buzz_feed">
<!-- corners -->
	<div class="round_10_tl corner_tl"></div>
	<div class="round_10_tr corner_tr"></div>
	<div class="round_10_bl corner_bl"></div>
	<div class="round_10_br corner_br"></div>
	<!-- control bar-->
	<div id="buzz_control" class="buzz_control rate_fav">
		
		
		<%= link_to "", item_vote_path(topic, :score => "1", :format => :js), :method => :post, :class => vote_status(topic, :btn_up), :remote => :true %>
		<p id="buzz_rate" class="buzz_rate"><%= topic.score %></p>
		<%= link_to "", item_vote_path(topic, :score => "-1", :format => :js), :method => :post, :class => vote_status(topic, :btn_down), :remote => :true %>

	</div>

	<!-- feed content -->
	<div id="buzz_content_holder" class="buzz_content_holder">
	  <%= link_to topic.title, topic.url, :class => :buzz_title, :id => :title %>

		<br />
    
    <%= link_to topic.author.username, "", :class => :buzz_author, :id => :author %>
    <%= t(:post_at) %>
		<span id="time" class="buzz_time"><%= time_ago_in_words topic.created_at %></span>
		<%= t(:ago) %>
		|<%= link_to "链接", item_path(topic) %>

		<p class="buzz_content"><%= topic.text %></p>

	</div>

	<div id="buzz_comment" class="buzz_comment">
	  <%= link_to "嗡一下", new_comment_path(:parent => topic), :remote => :true %>
		(<%= link_to tree_count(topic), item_path(topic)%>)
	</div>

</div>
<!--end of a feed-->

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/new.js.erb
$("#post_form").dialog({
  autoOpen: true,
  modal: true,
  width: 480,
  title: '新嗡嗡',
  position: ['center', 100],
  open: function() {
    disable_scroll()
    $("#post_form").html("<%= escape_javascript(render('form')) %>")
  },
  close: enable_scroll
});