config/routes.rb
Buzzbuzz::Application.routes.draw do
  devise_for :users
  
  resources :topics
  resources :comments

  resources :users
  
  resources :items do |route|
    post 'vote'
  end
  
  match '/best' => 'root#best'
  match '/recent' => 'root#recent'
  match '/worst' => 'root#worst'
  

  root :to => "root#best"

end

app/controllers/root_controller.rb
class RootController < ApplicationController
  before_filter :authenticate_user!
  
  def best
    @topics = Topic.content_for :best, :page => params[:page].to_i, :per_page => 15
    @type = 'best'
    respond_to do |format|
      format.html { render 'index' }
      format.js { render 'index' }
    end
  end
  
  def worst
    @topics = Topic.content_for :worst, :page => params[:page].to_i, :per_page => 15
    @type = 'worst'
    respond_to do |format|
      format.html { render 'index' }
      format.js { render 'index' }
    end
  end
  
  def recent
    @type = 'recent'
    @topics = Topic.content_for :recent, :page => params[:page].to_i, :per_page => 15
    respond_to do |format|
      format.html { render 'index' }
      format.js { render 'index' }
    end
  end
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/root/index.html.erb
<% javascript :defaults, 'endless_page', 'sidebar' %>
<div id="page_type" style="display:none"><%= @type %></div>
<div id="intro">
	<h1><%= t('.intro.title') %></h1>
	<p><%= t('.intro.detail')%><%= link_to t('.intro.link'), new_topic_path, :remote => true %></p>
</div>


<div id="main" class="">
	
	<!-- tab_bar -->
	<div id="tab_bar" class="clearfix">
		<ul id="tab_list">
			<li>
				<div class="tab_unselected_tl corner_tl"></div>
				<div class="tab_unselected_tr corner_tr"></div>
				<a href="/best">最好的</a>
			</li>
			<li>
				<div class="tab_unselected_tl corner_tl"></div>
				<div class="tab_unselected_tr corner_tr"></div>
				<a href="/recent">最近的</a>
			</li>
			<li>
				<div class="tab_unselected_tl corner_tl"></div>
				<div class="tab_unselected_tr corner_tr"></div>								
				<a href="worst">最烂的</a>
			</li>
		</ul>
	</div>

	<!-- feed-list -->
	<div id="feed_list_container" class="clearfix">
		<div class="round_15_tr corner_tr"></div>
		<div class="round_15_bl corner_bl"></div>
		<div class="round_15_br corner_br"></div>
		<div id="feed_list">
		  
		  <%= render :partial => @topics %>
		  
      
		</div>
		<div id="loading"></div>
	</div>
	<!--end of feed list-->

</div>

<!-- side bar -->
<div id="side_bar">
	<ul class="side_bar_clearfix">
		<li id="btn_buzz" ><%= link_to "", new_topic_path, :class => :btn_buzz, :remote => true %></li>
		<li id="btn_yell" ><%= link_to "", new_topic_path, :class => :btn_yell, :remote => true %></li>
	</ul>
	
	<div id="recent_comments_container">
		<div id="rc_title" class="rc_title">
			
		</div>
		<div id="rc_content_container" class="rc_content_container">
			<div class="round_15_tl corner_tl"></div>
			<div class="round_15_tr corner_tr"></div>
			<div class="round_15_bl corner_bl"></div>
			<div class="round_15_br corner_br"></div>			
			<div id="rc_content">
				<div id="rc_feed" class="rc_feed">
					<div class="round_10_tl corner_tl"></div>
					<div class="round_10_tr corner_tr"></div>
					<div class="round_10_bl corner_bl"></div>
					<div class="round_10_br corner_br"></div>
					<a>Absolutely. And the fact that he is merging onto another highway clinches it. it lends an air of mystery and exclusivity. why can't i take that road...where does it go?</a>
				</div>

				<div id="rc_feed" class="rc_feed">
					<div class="round_10_tl corner_tl"></div>
					<div class="round_10_tr corner_tr"></div>
					<div class="round_10_bl corner_bl"></div>
					<div class="round_10_br corner_br"></div>
					<a>Absolutely. And the fact that he is merging onto another highway clinches it. it lends an air of mystery and exclusivity. why can't i take that road...where does it go?</a>
				</div>

				<div id="rc_feed" class="rc_feed">
					<div class="round_10_tl corner_tl"></div>
					<div class="round_10_tr corner_tr"></div>
					<div class="round_10_bl corner_bl"></div>
					<div class="round_10_br corner_br"></div>
					<a>Absolutely. And the fact that he is merging onto another highway clinches it. it lends an air of mystery and exclusivity. why can't i take that road...where does it go?</a>
				</div>
			</div>

			
		</div>
	</div>
	<a id="scroll_to_top" style="display:none" href="#"></a>

</div>

app/views/root/index.js.erb
$("<%= escape_javascript(render(:partial => @topics)) %>").hide().appendTo('#feed_list').fadeIn(2000);

if (<%= @topics.total_page %> > <%= @topics.current_page %>) {
  checkScroll();
} else {
  $('#loading').hide()
}